---
# Services to enable
_xrdp_services_enable:
  all: []
  CentOS_7:
    - xrdp
  RedHat_7:
    - xrdp
  CentOS_8:
    - xrdp
  RedHat_8:
    - xrdp
  Fedora_31:
    - xrdp
  Debian_10:
    - xrdp
  Ubuntu_18:
    - xrdp
