---
# Configure xrdp

- name: enable service {{ item }}, and start if not started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ xrdp_services_enable }}"
  when: xrdp_enable_service
