---
# Template configuration files for xrdp

- name: template configuration {{ item.template }}
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ xrdp_templates_copy }}"
  when: xrdp_copy_templates
